// <auto-generated />
namespace FinalGroupProjectTeam8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig21));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051129389_mig21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
